# Generated by Django 3.0.7 on 2020-12-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRF_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='city',
            name='Timezone',
        ),
        migrations.RemoveField(
            model_name='city',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='city',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='Provision',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
