# Generated by Django 3.0.7 on 2020-12-09 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DRF_App', '0002_auto_20201209_0735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='Provision',
            new_name='Province',
        ),
    ]
